version: "3.9"

services:
  frontend:
    build: frontend
    ports:
      - 80:3000
    depends_on:
      - api
  api:
    build: api
    ports:
      - 5000:8080
    depends_on:
      - redis
  redis:
    image: redis:alpine
