# "production" docker-compose; this file is added by default by docker-compose,
# unless --file is specified and is skipped in dev-composition.sh

version: "3.9"

services:
  frontend:
    ports:
      - 8080:3000

  api:
    environment:
      FLASK_ENV: production
      FRONTEND_APP_URL: frontend:8080
