"""empty message

Revision ID: 24f54ba7d53f
Revises: eb768171dcce
Create Date: 2021-10-01 19:17:24.336475

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision = '24f54ba7d53f'
down_revision = 'eb768171dcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'token_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token_type', sa.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
