"""add cache.rating

Revision ID: 3b01865de320
Revises: a0ebc6df70c4
Create Date: 2022-02-25 19:18:47.266908

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "3b01865de320"
down_revision = "a0ebc6df70c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("caches", sa.Column("rating", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("caches", "rating")
    # ### end Alembic commands ###
