"""add cache.description

Revision ID: a0ebc6df70c4
Revises: eb768171dcce
Create Date: 2021-10-07 17:30:05.325333

"""

import sqlalchemy as sa
from alembic import op
from everycache_api.models import Cache

# revision identifiers, used by Alembic
revision = 'a0ebc6df70c4'
down_revision = 'eb768171dcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caches', sa.Column('description', sa.Text(), nullable=True))
    op.execute("UPDATE caches SET description = 'DEFAULT DESCRIPTION'")
    with op.batch_alter_table('caches', schema=None) as batch_op:
        batch_op.alter_column('description', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caches', 'description')
    # ### end Alembic commands ###
